import logging
import os
from datetime import datetime

logger = logging.getLogger(__name__)

REPORT_TITLE = "MECHANICAL TEST ANALYSIS"
SEPARATOR = "=" * 60


def generate_report(properties, summary, filepath,
                    material='Al-6061', condition='T6'):
    """Write a formatted text report to `filepath`."""
    # Ensure output directory exists
    parent = os.path.dirname(filepath)
    if parent:
        os.makedirs(parent, exist_ok=True)

    # Open file for writing
    with open(filepath, 'w', encoding="utf-8") as file:
        # ----- Header -----
        file.write(REPORT_TITLE + "\n")
        file.write(SEPARATOR + "\n")
        file.write(f"Date      : {datetime.now():%Y-%m-%d %H:%M}\n")
        file.write(f"Material  : {material}\n")
        file.write(f"Condition : {condition}\n")
        file.write(SEPARATOR + "\n\n")

        # ----- Data summary -----
        file.write("DATA SUMMARY\n")
        file.write(f"  Rows loaded        : {summary['after_filter_count']}\n")
        file.write(f"  Duplicates removed : {summary['duplicates_removed']}\n")
        file.write(f"  Final row count    : {summary['final_row_count']}\n\n")

        # ----- Mechanical properties -----
        file.write("MECHANICAL PROPERTIES\n")
        file.write(f"  Young's Modulus       : {properties['E_GPa']:.1f} GPa\n")
        file.write(f"  Yield Strength (0.2%) : {properties['Yield_MPa']:.1f} MPa\n")
        file.write(f"  Ultimate Tensile Str. : {properties['UTS_MPa']:.1f} MPa\n")
        file.write(f"  Elongation at Fracture: {properties['Elongation_pct']:.2f} %\n")
        file.write(f"  Toughness             : {properties['Toughness_MJ_m3']:.2f} MJ/m³\n\n")

        # ----- Work-hardening (only if computed) -----
        file.write("WORK-HARDENING ANALYSIS\n")
        if properties.get('n') is not None:
            file.write(f"  Hardening exponent n : {properties['n']:.3f}\n")
            file.write(f"  Strength coeff. K    : {properties['K_MPa']:.1f} MPa\n")
            file.write(f"  Fit quality R²       : {properties['R2']:.3f}\n\n")
        else:
            file.write("  Not computed (insufficient plastic region data)\n\n")

        # ----- Interpretation -----
        file.write("INTERPRETATION\n")
        file.write(build_interpretation(properties, material, condition))
        file.write("\n")

        # ----- Footer -----
        file.write(SEPARATOR + "\n")
        file.write("Generated by mechanical-test-analyzer\n")

    logger.info(f"Saved report: {filepath}")
    return filepath


def build_interpretation(properties, material, condition):
    """
    Build the interpretation section.

    Returns a multi-paragraph string; paragraphs are separated by a
    blank line so the reader's eye gets a break between points.
    """
    lines = []

    # --- Young's modulus ---
    E = properties['E_GPa']
    if 60 <= E <= 75:
        lines.append(
            f"The computed Young's modulus ({E:.1f} GPa) is consistent with "
            f"literature values for {material} (~68–70 GPa), indicating the "
            f"elastic region was correctly captured."
        )
    else:
        lines.append(
            f"Young's modulus ({E:.1f} GPa) deviates from the typical "
            f"~69 GPa for {material}; check elastic-region selection."
        )

    # --- Yield strength ---
    YS = properties['Yield_MPa']
    lines.append(
        f"The 0.2% offset yield strength is {YS:.1f} MPa, characteristic "
        f"of {material} in the {condition} temper."
    )

    # --- Ductility ---
    elong = properties['Elongation_pct']
    if elong >= 8:
        lines.append(
            f"Elongation at fracture ({elong:.2f}%) indicates reasonable "
            f"ductility, consistent with a precipitation-hardened aluminum "
            f"alloy."
        )
    else:
        lines.append(
            f"Elongation at fracture ({elong:.2f}%) is on the low side; "
            f"{condition} temper typically reduces ductility relative to "
            f"annealed conditions."
        )

    # --- Work hardening (with anomaly flag) ---
    if properties.get('n') is not None:
        n = properties['n']
        r2 = properties['R2']

        if 0.1 <= n <= 0.4:
            lines.append(
                f"The plastic region fits the Hollomon law σ = K·εⁿ with "
                f"n = {n:.3f} and R² = {r2:.3f}, consistent with typical "
                f"aluminum-alloy work-hardening behavior."
            )
        else:
            lines.append(
                f"The plastic region fits the Hollomon law σ = K·εⁿ with "
                f"n = {n:.3f} and R² = {r2:.3f}. Note: n falls outside the "
                f"typical 0.1–0.4 range for aluminum alloys. This is likely "
                f"because the T6 temper exhibits very little work hardening "
                f"in this specimen — the plastic region is nearly flat "
                f"before necking, giving a low log-log slope despite an "
                f"excellent fit quality."
            )

    # Return paragraphs separated by blank lines for readability
    return "\n\n".join(lines) + "\n"